version: "1.0.0"

services:
  dev-client:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - my_network

  dev-server:
    build: ./server
    ports:
      - "4000:4000"
    networks:
      - my_network

  redis:
    image: "redis:alpine"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
